;;; .loaddefs.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:


;;;### (autoloads nil "c-xrefactory/editors/emacs/c-xref" "c-xrefactory/editors/emacs/c-xref.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from c-xrefactory/editors/emacs/c-xref.el

(register-definition-prefixes "c-xrefactory/editors/emacs/c-xref" '("c-xref-" "cut-long-refactoring-undo-list" "get-corresponding-undo" "undo-changes-until"))

;;;***

;;;### (autoloads nil "c-xrefactory/editors/emacs/c-xrefactory" "c-xrefactory/editors/emacs/c-xrefactory.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from c-xrefactory/editors/emacs/c-xrefactory.el

(register-definition-prefixes "c-xrefactory/editors/emacs/c-xrefactory" '("c-xref-"))

;;;***

;;;### (autoloads nil "c-xrefactory/editors/emacs/c-xrefdoc" "c-xrefactory/editors/emacs/c-xrefdoc.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from c-xrefactory/editors/emacs/c-xrefdoc.el

(register-definition-prefixes "c-xrefactory/editors/emacs/c-xrefdoc" '("c-xref-refactoring-documentation"))

;;;***

;;;### (autoloads nil "c-xrefactory/editors/emacs/c-xrefprotocol"
;;;;;;  "c-xrefactory/editors/emacs/c-xrefprotocol.el" (0 0 0 0))
;;; Generated autoloads from c-xrefactory/editors/emacs/c-xrefprotocol.el

(register-definition-prefixes "c-xrefactory/editors/emacs/c-xrefprotocol" '("c-xref_"))

;;;***

;;;### (autoloads nil nil ("c-xrefactory/editors/emacs/compileCxrefactory.el")
;;;;;;  (0 0 0 0))

;;;***

;;; End of scraped data

;; Local Variables:
;; version-control: never
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .loaddefs.el ends here
