#!/bin/sh
rm -r -f ../c-xref

cd src
make
cd ..

# Create package distribution directory
mkdir ../c-xref

# Copy exercise directories
cp -r doc/jexercise ../c-xref/jexercise
cp -r doc/cexercise ../c-xref/cexercise

#create a text version of manual pages
#man doc/c-xref.man | sed -f doc/man2ascii.sed > doc/c-xref.txt
#man doc/c-xrefrc.man | sed -f doc/man2ascii.sed > doc/c-xrefrc.txt

# Copy executable
if test -f src/c-xref.exe
then
    cp src/c-xref.exe ../c-xref/
else
    cp src/c-xref ../c-xref/
fi

# Copy README files
cat doc/INSTALL doc/README doc/readme2 > ../c-xref/README
cp doc/INSTALL ../c-xref/INSTALL
cp doc/c-xrefsetup ../c-xref/
cp doc/c-xrefinstall ../c-xref/
cp doc/c-xref.man ../c-xref/
#cp doc/c-xref.txt ../c-xref/
cp doc/c-xrefrc.man ../c-xref/
#cp doc/c-xrefrc.txt ../c-xref/

# Copy relevant editor files
cd env
for d in *
do
    if [ "$d" != "jedit" ] ; then
        mkdir ../../c-xref/${d}
        for f in `cat ${d}/Files`
        do
            cp ${d}/${f} ../../c-xref/${d}/
        done
    fi
done

# Copy license files
cd ..
cp GPL.txt ../c-xref/GPL.txt
cp doc/LICENSE ../c-xref/LICENSE

# Finish up
cd ../c-xref
ln -s emacs xemacs
chmod -R a+r ../c-xref
