# Boilerplate Makefile for many c-xref tests
#
# - Names the test from directory name
# - Generates a specific, simple, c-xrefrc from a template
#
# In the test Makefiles you just need to include this and define the
# $(TEST) target where the execution of the test should go.
#

# Colours:
BLACK = 0
RED   = 1
GREEN = 2
YELLOW = 3
BLUE  = 4
MAGENTA = 5
CYAN  = 6
WHITE = 7

# OK and FAIL messages (with colour)
OK = echo "Tests in '$(TEST)': $(shell tput setaf $(GREEN))Ok$(shell tput sgr0)"
FAIL = echo "Tests in '$(TEST)': $(shell tput setaf $(RED))Failed$(shell tput sgr0)"

TEST = $(shell basename '$(CURDIR)')

all: .c-xrefrc $(TEST)

# Make all testcases silent by default. Use VERBOSE=1 to revert
# Automated tests for checking generated c-xreferences
$(VERBOSE).SILENT:

# All tests that uses a server driver should use this
EDIT_SERVER_DRIVER = ../../utils/server_driver.py

# Since absolute paths are abundant we need to...
NORMALIZE = sed -e "s+$(CURDIR)+CURDIR+g" -e "s/ len=[0-9]*/ len=<n>/g" -e "s+/.*/usr/+/usr/+g"

# Do we need date normalization too?
# -E 's/[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2} [[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}/0000-00-00 00:00:00/' >> output.tmp

# Verification is often done by comparing an output with the expected
VERIFY = cmp output expected ; \
	if [ $$? -ne 0 ] ; then \
		$(FAIL) ; \
		diff output expected ; \
		exit 1 ; \
	else \
		$(OK) ; \
		exit 0 ; \
	fi

# If the test requires a .c-xrefrc for test directory you need to
# generate one. The .c-xrefrc requires absolute paths, and to work in
# any directory, a .c-xrefrc can be generated from a common
# c-xrefrc.tpl by replacing some symbols as per rules below.
#
# We use the name '.c-xrefrc' so that a test can set HOME to CWD and
# editors will automatically read the correct file as if it was in the
# users HOME.
#
# TODO: we should check for a c-xrefrc.tpl in the test directory and
# use that instead, currently they have to do this in the Makefile if
# the standard does not work
.c-xrefrc: ../c-xrefrc.tpl
	@sed -e "s+CURDIR+$(CURDIR)+g" -e "s+TEST+$(TEST)+g" ../c-xrefrc.tpl > .c-xrefrc
