#!/bin/sh
#
# Shell script to run a program in the background with dotted visible feedback.
# The output will be collected in "output.run".
#
# Any arguments to this script will be used as c-xref options
#
$@ > output.run &
PROCID=$!
while kill -0 $PROCID > /dev/null 2>&1 ; do sleep 1 ; printf "." ; done
echo ""

wait "$PROCID"            # reap the child
EXIT_CODE=$?              # save exit code

if [ $EXIT_CODE -eq 139 ]; then
    echo "run-with-progress: Process terminated with SIGSEGV" >&2
elif [ $EXIT_CODE -ne 0 ]; then
    echo "run-with-progress: Process failed with exit code $EXIT_CODE" >&2
fi

exit $EXIT_CODE
