#!/bin/sh
#
# Shell script to run c-xref in the background with dotted visible feedback.
# The output will be collected in "out".
#
# Any arguments to this script will be used as c-xref options
#
../../src/c-xref -create -xrefrc .c-xrefrc -user 1 -xrefactory-II -crlfconversion -crconversion -encoding=default -exactpositionresolve "$@" > out &
PROCID=$!
while kill -0 $PROCID > /dev/null 2>&1 ; do sleep 1 ; printf "." ; done
