#! /bin/bash
# Run an autodiscovered test in the c-xrefactory test suite
# args: 1 = test (directory) name
#
# Environment variables:
#       GCOV_OPTIONS such as "GCOV_PREFIX=<path> GCOV_PREFIX_STRIP=6"
#
# Checks if the test is suspended and runs with the GCOV_OPTIONS

if [ -f $1/.suspended ] ; then
    echo "Tests in '$1': `tput setaf 6`SUSPENDED`tput sgr0`"
else
    mkdir -p $1/.coverage
    make --no-print-directory $GCOV_OPTIONS -C $1
    rc=$?
    if [ $rc -ne 0 ] ; then
	exit $rc
    fi
fi
