#! /bin/bash
# Run an autodiscovered test in the c-xrefactory test suite
# args: 1 = test (directory) name
#
# Environment variables:
#       GCOV_OPTIONS such as "GCOV_PREFIX=<path> GCOV_PREFIX_STRIP=6"
#
# Checks if the test is suspended and runs with the GCOV_OPTIONS

# TODO check for gcov-tool compatible with compiler used:

if [ -f $1/.suspended ] ; then
    echo "Tests in '$1': `tput setaf 6`SUSPENDED`tput sgr0`"
else
    mkdir -p $1/.coverage
    make --no-print-directory $GCOV_OPTIONS -C $1
    rc=$?
    if [ $rc -ne 0 ] ; then
	    exit $rc
    fi
    if ! command -v gcov-tool &> /dev/null ; then
        cd $1
        eval export $GCOV_OPTIONS
        # Then we create a coverage.info for this test
        lcov --version | grep -qv 'version 2' || lcovignore="--ignore-errors gcov,gcov --ignore-errors empty,empty --ignore-errors usage,usage"
        lcov -q $lcovignore -c -d .coverage -b ../../src --build-directory ../../src/.objects -o .coverage/coverage.info 2>&1 > /dev/null
    fi
fi
