== Software Architecture

=== Container View

image::embed:ContainerView[]

=== Containers

At this point the internal structure of the containers are
tentative. The actual interfaces are not particularly clean, most code
files can and do include much every other module.

NOTE: One focus area for the ongoing work is to try to pry out modules/components
from the code mess by moving functions around, renaming and hiding
functions, where possible.

==== CxrefCore

image::embed:CxrefCore[]

The `CxrefCore` container is the core container. It does all the work
when it comes to finding and reporting references to symbols,
communicating refactoring requests as well as storing reference
information for longer term storage and caching.

Its responsibilities can largely be divided into

* parsing source files to create, maintain the references database which stores all inter-module references
* parsing source files to get important information such as positions for a functions begin and end
* managing editor buffer state
* performing symbol navigation
* creating and serving completion suggestions
* performing refactorings such as renames, extracts and parameter manipulation


==== EditorExtension

image::embed:EditorExtension[]

The `EditorExtension` container is responsible for plugging into an
editor of choice and handle the user interface, buffer management and
executing the refactoring edit operations.

Currently there is only one such extension supported, for `Emacs`,
although there existed code, still available in the repo history, for
an extension for `jEdit` which hasn't been updated, modified or checked
for a long time and no longer is a part of this project.

==== ReferencesDB

The References database stores crossreferencing information for
symbols visible outside the module it is defined in. Information about
local/static symbols are gathered by parsing that particular source
file on demand.

Currently this information is stored in a cryptic, optimized text
format.