== Modules

The current state of `c-xrefactory` is not such that clean modules can
easily be identified and located. This is obviously one important goal
of the continuing refactoring work.

To be able to do that we need to understand the functionality enough
so that clusters of code can be refactored to be more and more clear
in terms of responsibilities and interfaces.

This section makes a stab at identifying some candidated to modules,
as illustrated by the component diagram for `cxrefCore`.

=== Yylex

==== Responsibilities

- Transform source text to sequences of lexems and additional
  information
- Register and apply C pre-processor macros and defines as well as
  defines made as command line options (`-D`)
- Handle include files by pushing and poping read contexts

==== Interface

The `yylex` module has the standard interface required by any
`yacc`-based parser, which is a simple `yylex(void)` function.

=== Parser

=== Xref

=== Server

=== Refactory

=== Cxref

=== Main

=== Cxfile

==== Responsibilities

Read and write the CXref database in "plain" text format.

==== File format

The current file format for the cross-reference data consists of records with the general format

    <number><key>[<value>]

There are two important types of lines, a file information line and a
symbol information line.

The actual keys are documented in `cxfile.c`, but here is an example
file information line:

    32571f  1715027668m 21:/usr/include/ctype.h

First we have two simple value/key pairs. We see "32571f" indicating
that this is file information for file with file number 32571.

Secondly we have "1715027668m". This is the modification time of the
file which is stored to be able to see if that file has been updated
since the reference database was last written.

And the third part is "21:/usr/include/ctype.h", which is of a record
type that is a bit more complex. The number is the length of the
value. The ':' indicates that the record is a filename.

=== Caching

=== c-xref.el

=== c-xrefactory.el