== Modules

The current state of `c-xrefactory` is not such that clean modules can
easily be identified and located. This is obviously one important goal
of the continuing refactoring work.

To be able to do that we need to understand the functionality enough
so that clusters of code can be refactored to be more and more clear
in terms of responsibilities and interfaces.

This section makes a stab at identifying some candidated to modules,
as illustrated by the component diagram for `cxrefCore`.

=== Yylex

==== Responsibilities

- Transform source text to sequences of lexems and additional
  information
- Register and apply C pre-processor macros and defines as well as
  defines made as command line options (`-D`)
- Handle include files by pushing and poping read contexts

==== Interface

The `yylex` module has the standard interface required by any
`yacc`-based parser, which is a simple `yylex(void)` function.

=== Parser

=== Xref

=== Server

=== Refactory

=== Cxref

=== Main

=== Memory

==== Background

Although the memory "module" is not shown in the component diagram, it is very
important. And it has also been a source for grievances and confusion as it is, and
probably still are, contrieved and not so easy to understand.

The main "design" restricition for the design of the memory handling is the fact that in
the early days, actual memory was scarce. To be able to cross-reference anything except
the smallest systems, the fact that the amount of memory available was insufficient had
to be handled.

Most of the memory types uses a statically allocated area inside which allocation can be
done, this applies to memory for pre-processor information for example. These sizes
could be extended only by re-compilation with a larger size for that type of memory.

However, for the most important memory type, the `cxMemory`, it could be handled
dynamically by detecting the out-of-memory situation and then discard, flush and re-use
the memory.

The size of the `cxMemory` could also be extended up to the defined maximum size.

This in turn, forced the implementation of a caching strategy, since this overflow may
happen during the reading of a file. This incurred much complexity.

==== Future direction

As virtual memory for a process in a modern OS is much larger than in the 1990's it
would not be impossible to remove this strategy of overflow detection and
recovery.

A possibility to in an orderly fashion flush and reuse memory would still be needed.

A new type of memory, `FlushableMemory`, has been implemented but as yet, not officially
replaced the current memory handling.

=== Cxfile

==== Responsibilities

Read and write the CXref database in "plain" text format.

==== File format

The current file format for the cross-reference data consists of records with the general format

    <number><key>[<value>]

There are two important types of lines, a file information line and a
symbol information line.

The actual keys are documented in `cxfile.c`, but here is an example
file information line:

    32571f  1715027668m 21:/usr/include/ctype.h

First we have two simple value/key pairs. We see "32571f" indicating
that this is file information for file with file number 32571.

Secondly we have "1715027668m". This is the modification time of the
file which is stored to be able to see if that file has been updated
since the reference database was last written.

And the third part is "21:/usr/include/ctype.h", which is of a record
type that is a bit more complex. The number is the length of the
value. The ':' indicates that the record is a filename.

=== c-xref.el

=== c-xrefactory.el