== Data Structures

There are a lot of different data structures used in `c-xrefactory`.
This is a first step towards visualising some of them.

=== ReferenceItems and References

This is a fundamental pair. A `ReferenceItem` is the symbol that
occurs at the locations that `References` indicate.

Each `ReferenceItem` has a linked list of `Reference`s, each denoting
one occurence of that "symbol".

=== Symbols and References

There is also a structure called `Symbol`. But, why is there no
connection between the symbols and the references?!?

So what are these actually?

[plantuml, structures, png]
....
class Symbol {
char *name
Position position
SymbolBits bits
}
Symbol o-- Symbol : next

class SymbolList {
}
SymbolList o-- Symbol : symbol
SymbolList o-- SymbolList : next

class ReferencesItem {
char *name
ReferencesBits bits
}
ReferencesItem o-- Reference : references
ReferencesItem o-- ReferencesItem : next

class Reference {
Usage usage
Position position
}
Reference o-- Reference : next

....

=== Files and Buffers

Many strange things are going on with reading files so that is not completely understood yet.

Here is an initial attempt at illustrating how some of the file and text/lexem buffers are related.

[plantuml, buffer, png]
....
class FileDescriptor {
}
FileDescriptor o-- LexemBuffer : lexemBuffer

class LexemBuffer {
  Lexem[] lexemStream
}
LexemBuffer o-- CharacterBuffer : buffer

class CharacterBuffer {
  char[] : chars
}

class LexemStream {
  char* : macroName
  InputType : inputType
}
LexemStream --> LexemBuffer : beginningOfBuffer, endOfBuffer, currentLexemP (into .lexemStream)
....

NOTE: It would be nice if the `LexemStream` structure could point to a
`LexemBuffer` instead of holding separate pointers which are
impossible to know what they actually point to...

NOTE: This could be achieved if we could remove the CharacterBuffer
from LexemBuffer and make that a reference instead of a
composition. Then we'd need to add a CharacterBuffer to the structures
that has a LexemBuffer as a component (if they use it).

=== Modes

`c-xrefactory` operates in different modes ("regimes" in original
`c-xref` parlance):

- xref - batch mode reference generation
- server - editor server
- refactory - refactory browser

The default mode is "xref". The command line options `-server` and `-refactory`
selects one of the other modes. Branching is done in the final lines in
`main()`.

The code for the modes are intertwined, probably through re-use of
already existing functionality when extending to a refactoring
browser.

One evidence for this is that the refactory module calls the "main
task" as a "sub-task".  This forces some intricate fiddling with the
options data structure, like copying it.  Which I don't
fully understand yet.

TODO?: Strip away the various "regimes" into more separated concerns
and handle options differently.

=== Options

The `Options` datastructure is used to collect options from the
command line as well as from options/configuration files and piped
options from the editor client using process-to-process
communication.

It consists of a collection of fields of the types

- elementary types (bool, int, ...)
- string (pointers to strings)
- lists of strings (linked lists of pointers to strings)

==== Allocation & Copying

Options has its own allocation using `optAlloc` which allocates in a
separate area, currently part of the options structure and utilizing
"dynamic allocation" (`dm_` functions on the `Memory` structure).

The Options structure are copied multiple times during a session, both
as a backup (`savedOptions`) and into a separate options structure
used by the Refactorer (`refactoringOptions`).

Since the options memory is then also copied, all pointers into the
options memory need to be updated. To be able to do this, the options
structure contains lists of addresses that needs to by "shifted".

When an option with a string or string list value is modified the
option is registered in either the list of string valued options or
the list of string list valued options. When an options structure is
copied it must be performed using a deep copy function which "shifts"
those options and their values (areas in the options memory) in the
copy so that they point into the memory area of the copy, not the
original.

After the deep copy the following point into the option memory of the
copy

- the lists of string and string list valued options (option fields)
- all string and string valued option fields that are used (allocated)
- all list nodes for the used option (allocated)
- all list nodes for the string lists (allocated)



