== Insights

This chapter contains notes of all insights, large and small, that I make as I work on this project.
These insights should at some point be moved to some other, more structured, part of this document.
But rather than trying to find a structure where each new finding fits, I'm making it easy to just dump them here.
We can refactor these into a better and better structure as we go.

=== Yacc semantic data

As per usual a Yacc grammar requires each non-terminal to have a type.
Those types are named after which types of data they collect and
propagate.  The names always starts with `ast_` and then comes the
data type.  For example if some non-terminal needs to propagate a
Symbol and a Position that structure would be called
`ast_symbolParameterPair` ("Pair" being thrown in there for good
measure...).

Each of those structures also always carries a begin and end position
for that structure.  That means that any "ast" struct has three
fields, `begin`, `end` and the data.  The data are sometimes a struct,
like in this case, but can also be a single value, like an `int` or a
pointer to a `Symbol`.

[plantuml, ast, png]
....

class ast_symbolPositionPair {
Position begin
Position end
}

ast_symbolPositionPair *-- SymbolPositionPair : data

class SymbolPositionPair {
Symbol *symbol
Position position
}

....

