#!/bin/sh
#
# usage: jar2jar archiv1 [ .. archivn ]
#
# jar2jar - convert compressed jar archives into uncompressed
#           so that they can be used by tools like xref.
# (c) 2001 by Xref-Tech, Bratislava
#
#
if test X$1 = X
then 
	echo "usage: jar2jar archiv1 [ .. archivn ]"
	exit
fi
#check if jar command exists
if echo | jar t
then
	echo > /dev/null
else
	echo "jar2jar: jar archiver not found"
fi
#
OPWD=${PWD}
TMPDIR=/tmp
for f in $*
do
	cd ${TMPDIR}  || exit
	mkdir jar2jar.$$   || exit
	cd jar2jar.$$ || exit
	if test `expr substr ${f} 1 1` = "/"
	then
		ff=${f}
	else
		ff=${OPWD}/${f}
	fi
	echo "Extracting '${ff}' to '${TMPDIR}/jar2jar.$$'"
 	jar -xf ${ff}  || exit
	echo "Updating archive"
	jar -uf0 ${ff} *
	cd ${TMPDIR} || exit
	echo "Cleaning"
	rm -r -f jar2jar.$$
done


