@startuml c-xref-context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define SPRITESURL https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.0/sprites
!include SPRITESURL/emacs.puml

LAYOUT_WITH_LEGEND()

Person(developer, "Developer", "Edits source code using an editor")
System(editor, "Editor", "Allows Developer to modify source code and perform refactoring operations", $sprite="emacs")
SystemDb(sourceCode, "Source Code")
System_Boundary(cxref, "c-xrefactory Browser") {
  Container(editorExtension, "Editor Extension", "Plugin", "Extends the Editor with c-xref operations and interfaces to the c-xrefactory API")
  Container(cxrefCore, "c-xref", "C Language program", "Refactoring Browser core")
  Container(settingsStore, "settings", "Non-standard format settings file", "Configuration file for project settings")
  ContainerDb(tagsDB, "tagsDB", "Source Code information storage", "Stores all information about the source code in the project which is updated by scanning all or parts of it when required.")
}

Rel(cxrefCore, settingsStore, "read")
Rel(editorExtension, settingsStore, "writes", "new project wizard")
Rel(editorExtension, cxrefCore, "API", "To request information and get modified code")
Rel(developer, editor, "GUI", "Usual editor/IDE operations")
Rel(editor, editorExtension, "Extends", "Editors extension protocol")
Rel(developer, settingsStore, "edit")
Rel(cxrefCore, tagsDB, "read/write")
Rel(cxrefCore, sourceCode, "read/analyze")
Rel(editor, sourceCode, "normal editing operations")
Rel(editorExtension, sourceCode, "extended c-xrefactory operations")
@enduml