                                                                       

;;; c-xrefprotocol.el - C-xrefactory protocol constants -*- lexical-binding: t; -*-
;;; DO NOT EDIT!!!
;;; AUTOGENERATED from src/protocol & src/refactorings using Makefile






























