





;;; DO NOT EDIT!!!
;;; AUTOGENERATED from src/protocol & src/refactorings using Makefile

(defconst C_XREF_FILE_VERSION_NUMBER "1.6.0")

(defconst PPC_NO_TAG "-- no tag --")

(defconst PPC_VERSION_MISMATCH "version-mismatch")

(defconst PPC_FULL_MULTIPLE_COMPLETIONS "full-completions")
(defconst PPC_ALL_COMPLETIONS "all-completions")
(defconst PPC_MULTIPLE_COMPLETION_LINE "cl")
(defconst PPC_SINGLE_COMPLETION "single-completion")
(defconst PPC_FQT_COMPLETION "fqt-completion")
(defconst PPC_SYMBOL_LIST "symbol-list")

(defconst PPC_CALL_MACRO "macro")
(defconst PPC_REFACTORING_PRECHECK "precheck")

(defconst PPC_REFACTORING_REPLACEMENT "replacement")
(defconst PPC_REFACTORING_CUT_BLOCK "cut-block")
(defconst PPC_REFACTORING_COPY_BLOCK "copy-block")
(defconst PPC_REFACTORING_PASTE_BLOCK "paste-block")


(defconst PPC_ASK_CONFIRMATION "ask-confirmation")
(defconst PPC_ADD_TO_IMPORTS_DIALOG "add-to-imports-dialog")
(defconst PPC_EXTRACTION_DIALOG "extraction-dialog")
(defconst PPC_DISPLAY_CLASS_TREE "display-class-tree")

(defconst PPC_DISPLAY_RESOLUTION "display-resolution")
(defconst PPC_DISPLAY_OR_UPDATE_BROWSER "display-or-update-browser")
(defconst PPC_SYMBOL_RESOLUTION "resolution")
(defconst PPC_SYMBOL "symbol")
(defconst PPC_VIRTUAL_SYMBOL "virtual-symbol")
(defconst PPC_CLASS "class")

(defconst PPC_REFERENCE_LIST "reference-list")
(defconst PPC_SRC_LINE "src-line")
(defconst PPC_UPDATE_CURRENT_REFERENCE "update-current-refn")

(defconst PPC_NO_PROJECT "no-project-found")
(defconst PPC_NO_SYMBOL "no-symbol-found")
(defconst PPC_SET_INFO "set-info")
(defconst PPC_WARNING "warning")
(defconst PPC_BOTTOM_WARNING "bottom-warning")
(defconst PPC_ERROR "error")
(defconst PPC_LICENSE_ERROR "license-error")
(defconst PPC_FATAL_ERROR "fatalError")
(defconst PPC_INFORMATION "information")
(defconst PPC_BOTTOM_INFORMATION "bottom-information")
(defconst PPC_DEBUG_INFORMATION "debug-information")

(defconst PPC_GOTO "goto")
(defconst PPC_BROWSE_URL "browse-url")
(defconst PPC_FILE_SAVE_AS "file-save-as")
(defconst PPC_MOVE_FILE_AS "file-move-as")
(defconst PPC_KILL_BUFFER_REMOVE_FILE "kill-buffer-remove-file")
(defconst PPC_MOVE_DIRECTORY "move-directory")
(defconst PPC_INDENT "indent-block")

(defconst PPC_IGNORE "ignore")
(defconst PPC_PROGRESS "progress")

(defconst PPC_UPDATE_REPORT "update-report")

(defconst PPC_AVAILABLE_REFACTORINGS "available-refactorings")

(defconst PPC_SYNCHRO_RECORD "sync")


(defconst PPC_LC_POSITION "position-lc")
(defconst PPC_OFFSET_POSITION "position-off")
(defconst PPC_STRING_VALUE "str")
(defconst PPC_INT_VALUE "int")


(defconst PPCA_LEN "len")
(defconst PPCA_LINE "line")
(defconst PPCA_COL "col")
(defconst PPCA_OFFSET "off")
(defconst PPCA_VALUE "val")
(defconst PPCA_LEVEL "lev")
(defconst PPCA_VCLASS "vcl")
(defconst PPCA_SELECTED "selected")
(defconst PPCA_BASE "base")
(defconst PPCA_DEF_REFN "drefn")
(defconst PPCA_REFN "refn")
(defconst PPCA_TYPE "type")
(defconst PPCA_MTYPE "mtype")
(defconst PPCA_CONTINUE "continue")
(defconst PPCA_INTERFACE "interface")
(defconst PPCA_INDENT "indent")
(defconst PPCA_TREE_DEPS "deps")
(defconst PPCA_TREE_UP "up")
(defconst PPCA_DEFINITION "definition")
(defconst PPCA_SYMBOL "symbol")
(defconst PPCA_BEEP "beep")
(defconst PPCA_NUMBER "number")
(defconst PPCA_NO_FOCUS "nofocus")


(defconst PPCV_BROWSER_TYPE_INFO 0)
(defconst PPCV_BROWSER_TYPE_WARNING 1)



(defconst PPC_AVR_NO_REFACTORING 0)
(defconst PPC_AVR_RENAME_SYMBOL 10)
(defconst PPC_AVR_RENAME_CLASS 20)
(defconst PPC_AVR_RENAME_PACKAGE 30)
(defconst PPC_AVR_ADD_PARAMETER 40)
(defconst PPC_AVR_DEL_PARAMETER 50)
(defconst PPC_AVR_MOVE_PARAMETER 60)
(defconst PPC_AVR_MOVE_STATIC_FIELD 70)
(defconst PPC_AVR_MOVE_STATIC_METHOD 80)
(defconst PPC_AVR_MOVE_FIELD 90)
(defconst PPC_AVR_TURN_DYNAMIC_METHOD_TO_STATIC 100)
(defconst PPC_AVR_TURN_STATIC_METHOD_TO_DYNAMIC 110)
(defconst PPC_AVR_PULL_UP_FIELD 120)
(defconst PPC_AVR_PULL_UP_METHOD 130)
(defconst PPC_AVR_PUSH_DOWN_FIELD 140)
(defconst PPC_AVR_PUSH_DOWN_METHOD 150)
(defconst PPC_AVR_MOVE_CLASS 160)
(defconst PPC_AVR_MOVE_CLASS_TO_NEW_FILE 170)
(defconst PPC_AVR_MOVE_ALL_CLASSES_TO_NEW_FILE 180)
(defconst PPC_AVR_ENCAPSULATE_FIELD 190)
(defconst PPC_AVR_SELF_ENCAPSULATE_FIELD 200)
(defconst PPC_AVR_ADD_TO_IMPORT 210)
(defconst PPC_AVR_EXTRACT_METHOD 220)
(defconst PPC_AVR_EXTRACT_FUNCTION 230)
(defconst PPC_AVR_EXTRACT_MACRO 240)
(defconst PPC_AVR_EXTRACT_VARIABLE 250)
(defconst PPC_AVR_REDUCE_NAMES 260)
(defconst PPC_AVR_EXPAND_NAMES 270)
(defconst PPC_AVR_ADD_ALL_POSSIBLE_IMPORTS 280)
(defconst PPC_AVR_SET_MOVE_TARGET 290)
(defconst PPC_AVR_UNDO 300)


