





;;; DO NOT EDIT!!!
;;; AUTOGENERATED from src/protocol & src/refactorings using Makefile

(defconst c-xref_PPC_NO_TAG "-- no tag --")

(defconst c-xref_PPC_VERSION_MISMATCH "version-mismatch")

(defconst c-xref_PPC_FULL_MULTIPLE_COMPLETIONS "full-completions")
(defconst c-xref_PPC_ALL_COMPLETIONS "all-completions")
(defconst c-xref_PPC_MULTIPLE_COMPLETION_LINE "cl")
(defconst c-xref_PPC_SINGLE_COMPLETION "single-completion")
(defconst c-xref_PPC_SYMBOL_LIST "symbol-list")

(defconst c-xref_PPC_CALL_MACRO "macro")
(defconst c-xref_PPC_REFACTORING_PRECHECK "precheck")

(defconst c-xref_PPC_REFACTORING_REPLACEMENT "replacement")
(defconst c-xref_PPC_REFACTORING_CUT_BLOCK "cut-block")
(defconst c-xref_PPC_REFACTORING_COPY_BLOCK "copy-block")
(defconst c-xref_PPC_REFACTORING_PASTE_BLOCK "paste-block")


(defconst c-xref_PPC_ASK_CONFIRMATION "ask-confirmation")
(defconst c-xref_PPC_EXTRACTION_DIALOG "extraction-dialog")

(defconst c-xref_PPC_DISPLAY_RESOLUTION "display-resolution")
(defconst c-xref_PPC_DISPLAY_OR_UPDATE_BROWSER "display-or-update-browser")
(defconst c-xref_PPC_SYMBOL_RESOLUTION "resolution")
(defconst c-xref_PPC_SYMBOL "symbol")

(defconst c-xref_PPC_REFERENCE_LIST "reference-list")
(defconst c-xref_PPC_SRC_LINE "src-line")

(defconst c-xref_PPC_NO_PROJECT "no-project-found")
(defconst c-xref_PPC_PROJECT_MISMATCH "project-mismatch")
(defconst c-xref_PPC_NO_SYMBOL "no-symbol-found")
(defconst c-xref_PPC_SET_INFO "set-info")
(defconst c-xref_PPC_WARNING "warning")
(defconst c-xref_PPC_BOTTOM_WARNING "bottom-warning")
(defconst c-xref_PPC_ERROR "error")
(defconst c-xref_PPC_FATAL_ERROR "fatalError")
(defconst c-xref_PPC_INFORMATION "information")
(defconst c-xref_PPC_BOTTOM_INFORMATION "bottom-information")
(defconst c-xref_PPC_DEBUG_INFORMATION "debug-information")

(defconst c-xref_PPC_GOTO "goto")
(defconst c-xref_PPC_FILE_SAVE_AS "file-save-as")
(defconst c-xref_PPC_MOVE_FILE_AS "file-move-as")
(defconst c-xref_PPC_KILL_BUFFER_REMOVE_FILE "kill-buffer-remove-file")
(defconst c-xref_PPC_MOVE_DIRECTORY "move-directory")
(defconst c-xref_PPC_INDENT "indent-block")

(defconst c-xref_PPC_IGNORE "ignore")
(defconst c-xref_PPC_PROGRESS "progress")

(defconst c-xref_PPC_UPDATE_REPORT "update-report")

(defconst c-xref_PPC_AVAILABLE_REFACTORINGS "available-refactorings")

(defconst c-xref_PPC_SYNCHRO_RECORD "sync")


(defconst c-xref_PPC_LC_POSITION "position-lc")
(defconst c-xref_PPC_OFFSET_POSITION "position-off")
(defconst c-xref_PPC_STRING_VALUE "str")
(defconst c-xref_PPC_INT_VALUE "int")


(defconst c-xref_PPCA_LEN "len")
(defconst c-xref_PPCA_LINE "line")
(defconst c-xref_PPCA_COL "col")
(defconst c-xref_PPCA_OFFSET "off")
(defconst c-xref_PPCA_VALUE "val")
(defconst c-xref_PPCA_LEVEL "lev")
(defconst c-xref_PPCA_VCLASS "vcl")
(defconst c-xref_PPCA_SELECTED "selected")
(defconst c-xref_PPCA_DEF_REFN "drefn")
(defconst c-xref_PPCA_REFN "refn")
(defconst c-xref_PPCA_TYPE "type")
(defconst c-xref_PPCA_MTYPE "mtype")
(defconst c-xref_PPCA_CONTINUE "continue")
(defconst c-xref_PPCA_INTERFACE "interface")
(defconst c-xref_PPCA_INDENT "indent")
(defconst c-xref_PPCA_TREE_DEPS "deps")
(defconst c-xref_PPCA_TREE_UP "up")
(defconst c-xref_PPCA_DEFINITION "definition")
(defconst c-xref_PPCA_SYMBOL "symbol")
(defconst c-xref_PPCA_BEEP "beep")
(defconst c-xref_PPCA_NUMBER "number")
(defconst c-xref_PPCA_NO_FOCUS "nofocus")


(defconst c-xref_PPCV_BROWSER_TYPE_INFO 0)
(defconst c-xref_PPCV_BROWSER_TYPE_WARNING 1)



(defconst c-xref_PPC_AVR_NO_REFACTORING 0)
(defconst c-xref_PPC_AVR_RENAME_SYMBOL 10)
(defconst c-xref_PPC_AVR_RENAME_MODULE 30)
(defconst c-xref_PPC_AVR_ADD_PARAMETER 40)
(defconst c-xref_PPC_AVR_DEL_PARAMETER 50)
(defconst c-xref_PPC_AVR_MOVE_PARAMETER 60)
(defconst c-xref_PPC_AVR_MOVE_FUNCTION 70)
(defconst c-xref_PPC_AVR_RENAME_INCLUDED_FILE 80)
(defconst c-xref_PPC_AVR_ORGANIZE_INCLUDES 90)
(defconst c-xref_PPC_AVR_EXTRACT_FUNCTION 230)
(defconst c-xref_PPC_AVR_EXTRACT_MACRO 240)
(defconst c-xref_PPC_AVR_EXTRACT_VARIABLE 250)
(defconst c-xref_PPC_AVR_SET_MOVE_TARGET 290)
(defconst c-xref_PPC_AVR_UNDO 300)


