#!/usr/bin/env python3
#
# Read information from cxref-files

import os
import sys
import argparse

import cxref_db
from cxref_db import (eprint, skip_header, unpack_xfiles, unpack_file_lines,
                      unpack_symbols, get_filename_from_id, read_lines_from)


def vprint(*args, **kwargs):
    if verbose:
        print(*args, file=sys.stderr, **kwargs)


def verify_directory(directory_name):
    if not os.path.exists(directory_name):
        eprint("ERROR: directory '%s' does not exist, point to a c-xref index directory" %
               directory_name)
        sys.exit()

    if not os.path.isdir(directory_name):
        eprint("ERROR: '%s' is not a directory, should be a c-xref index directory" %
               directory_name)
        sys.exit()

    if not os.path.exists(os.path.join(directory_name, "XFiles")):
        eprint("ERROR: '%s' does not contain an 'XFiles' file" % directory_name)
        sys.exit()


if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        description='Read the CXref db of c-xrefactory and present the symbols in readable format.')
    parser.add_argument('-v', '--verbose',
                        help='verbose output', action='store_true')
    parser.add_argument(
        'path', help='the CXref db to read, directory or single file, default is CXrefs', nargs='?', default='CXrefs')

    args = parser.parse_args()

    directory_name = args.path
    if args.verbose:
        verbose = True
    else:
        verbose = False

    symbols = []

    # Check if path exists
    if not os.path.exists(args.path):
        eprint("ERROR: '%s' does not exist" % args.path)
        sys.exit(1)

    if os.path.isdir(args.path):
        verify_directory(directory_name)

        # Get all file references from the XFiles file
        vprint("Unpacking", "XFiles")
        lines = read_lines_from(directory_name, "XFiles")
        lines = skip_header(lines)
        files = unpack_xfiles(lines)
        cxref_db.files = files

        # Read all CXref-files and list identifiers
        for cxfilename in sorted(os.listdir(directory_name)):
            if cxfilename != "XFiles" :
                vprint("Unpacking", cxfilename)
                lines = read_lines_from(directory_name, cxfilename)
                lines = skip_header(lines)
                symbols += unpack_symbols(lines)
    else:
        # Single file case (e.g., when -refnum=1)
        lines = read_lines_from("", args.path)
        lines = skip_header(lines)
        (files, lines) = unpack_file_lines(lines)
        cxref_db.files = files
        # In single-file format, the compact record state flows from file
        # entries into symbol records.  Initialize marker_value['f'] so
        # references that omit the 'f' marker inherit the last file entry.
        if files:
            cxref_db.marker_value['f'] = files[-1].fileid
        symbols = unpack_symbols(lines)

    symbols.sort(key=lambda s: s.symbolname)
    for symbol in symbols:
        print(symbol.symbolname)
        symbol.references.sort(key=lambda r: (os.path.basename(get_filename_from_id(r.fileid, files)),
                                               r.lineno if r.lineno else 0,
                                               r.colno if r.colno else 0))
        for p in symbol.references:
            # Save fileid, lineno and colno in case any of them are skipped in next symbol in this file
            filename = get_filename_from_id(p.fileid, files)
            filename = os.path.basename(filename)
            print("    @%s:%d:%d" %
                  (filename, p.lineno if p.lineno else 0, p.colno if p.colno else 0))
