#!/bin/sh
#
# This is a script that aims at running a virgin Emacs with minimal c-xrefactory setup
# with the development versions of everything (which means that there should be a freshly
# compiled src/c-xref available. This is to ensure no interference with your own setup.

PPWD=`pwd`

# Start by creating an init-file for emacs
echo "(setq load-path (cons \"${PPWD}/env/emacs\" load-path))" > /tmp/dev-emacs.el
echo "(setq exec-path (cons \"${PPWD}/src\" exec-path))" >> /tmp/dev-emacs.el
echo "(load \"c-xrefactory\")" >> /tmp/dev-emacs.el

# Then start emacs with it, set HOME so not to create cx-ref-files in your home
HOME=/tmp emacs --no-splash --load /tmp/dev-emacs.el $*
