#! /bin/env bash
#
# Simple Emacs startup using latest development version
#
set -x
PWD="$(dirname "$(realpath "$0")")"

FILES=$(find "$PWD/../editors/emacs" -type f -name "*.el" ! -name "compileCxrefactory.el")
LOAD_FILES=$(printf " -l %q" $FILES)

# Check if .c-xrefrc exists in the current directory
if [[ -f .c-xrefrc ]]; then
  OPTIONS_FILE="\"$PWD/.c-xrefrc\""
else
  OPTIONS_FILE=""
fi

# Construct Emacs command with proper quoting
if [[ -n "$OPTIONS_FILE" ]]; then
  emacs $LOAD_FILES \
    --eval "(setq c-xref-options-file $OPTIONS_FILE)" \
    --eval "(setq c-xref-exec-directory \"$PWD/../src/\")" \
    --eval "(setq c-xref-debug-mode t)" \
    --eval "(setq c-xref-debug-preserve-tmp-files t)" \
    "$@"
else
  emacs $LOAD_FILES \
    --eval "(setq c-xref-exec-directory \"$PWD/../src/\")" \
    --eval "(setq c-xref-debug-mode t)" \
    --eval "(setq c-xref-debug-preserve-tmp-files t)" \
    "$@"
fi
