#! /bin/env bash
#
# Simple Emacs startup using latest development version
#
UTILS="$(dirname "$(realpath "$0")")"

FILES=$(find "$UTILS/../editors/emacs" -type f -name "*.el" ! -name "compileCxrefactory.el")
LOAD_FILES=$(printf " -l %q" $FILES)

# Ensure we don't load compiled stuff
rm -f $UTILS/../editors/emacs/*.elc

# Check if .c-xrefrc exists in the current directory
if [[ -f .c-xrefrc ]]; then
  OPTIONS_FILE="\"$PWD/.c-xrefrc\""
else
  OPTIONS_FILE=""
fi

echo "$@"

# Construct Emacs command with proper quoting
if [[ -n "$OPTIONS_FILE" ]]; then
  emacs $LOAD_FILES \
    --eval "(setq c-xref-options-file $OPTIONS_FILE)" \
    --eval "(setq c-xref-exec-directory \"$UTILS/../src/\")" \
    --eval "(setq c-xref-debug-mode t)" \
    --eval "(setq c-xref-debug-preserve-tmp-files t)" \
    --eval "(setq lsp-auto-activate nil)" \
    "$@"
else
  emacs $LOAD_FILES \
    --eval "(setq c-xref-exec-directory \"$UTILS/../src/\")" \
    --eval "(setq c-xref-debug-mode t)" \
    --eval "(setq c-xref-debug-preserve-tmp-files t)" \
    --eval "(setq lsp-auto-activate nil)" \
    "$@"
fi
