#!/usr/bin/env bash
#
# Simple Emacs startup for lsp-mode using c-xrefactory-lsp development version
#
UTILS="$(dirname "$(realpath "$0")")"

emacs --no-splash -l $UTILS/lsp-initialize.el $@ &
emacs_pid=$!
read -p "Ange PID för processen du vill debugga: " pid
if [ -z "$pid" ]; then
    echo "Ingen PID angiven. Avbryter."
    exit 1
fi
echo "Startar gdb mot PID $pid..."
gdb -q -p $pid -ex 'br internalCheckFail'
kill $emacs_pid
