#!/bin/sh
#
# This is a script that aims at running a virgin Emacs with minimal c-xrefactory setup
# with the development versions of everything (which means that there should be a freshly
# compiled src/c-xref available. This is to ensure no interference with your own setup.
#
# NB WIP

PPWD=`pwd`
PID=$$

DIR=/tmp/c-xref-emacs-$PID

# Create a temporary directory
mkdir $DIR

# How to create an .emacs with an el-lisp installation including c-xrefactory?

# Create an init-file for emacs
echo "(setq load-path (cons \"${PPWD}/env/emacs\" load-path))" > $DIR/dev-emacs.el
echo "(setq exec-path (cons \"${PPWD}/src\" exec-path))" >> $DIR/dev-emacs.el
echo "(load \"c-xrefactory\")" >> $DIR/dev-emacs.el

# Then start emacs with it, set HOME so not to create cx-ref-files in your home
HOME=$DIR emacs --no-splash --load $DIR/dev-emacs.el $*
