#! /bin/bash

# Use the coverage from a single integration test to generate .gcov
# files in src directory $1 is the path to a directory, presumably in
# tests, a test directory and it should have a .coverage subdirectory

rm *.gcov
cp $1/.coverage/*.gcda .objects
gcov .objects/*.o --object-directory .objects | grep "File"
