#ifndef _ENUMTXT_H_
#define _ENUMTXT_H_

/* Here are declarations of enum name strings generated by c-xref
   itself. See Makefile.common for how it's done. We use existing
   versions to build c-xref and then regenerate the two files to see
   if they differ. If so you need to recompile and then commit the
   files to the repo.

   NOTE: previously it was done the other way around a separate file
   was used to build a bootstrap version first. This way we don't need
   the bootstrap step.
 */
#include "enumTxt.g.h"

#endif
