#########################################################################
CC= gcc
COMCFLAGS= $(INCLUDES) -DDEBUG $(ZLIB_OPT) \
			-DPRESERVE_C_ARGS -DGNULINUXDEFS
CFLAGS= -c -O $(COMCFLAGS) -Wno-long-double
LDFLAGS=
LEX=flex
YACC=$(ROOTDIR)/../byacc-1.9/yacc
RANLIB=ranlib
ROOTDIR=..
#########################################################################


include Makefile.common
include Makefile.dependencies


#########################################################################
