#########################################################################
CC= gcc
COMCFLAGS= $(INCLUDES) -DDEBUG $(ZLIB_OPT) \
			-DPRESERVE_C_ARGS -DGNULINUXDEFS
CFLAGS= -c -O $(COMCFLAGS)
LDFLAGS= -static
BIN=$(HOME)/bin
LEX=flex
YACC=$(ROOTDIR)/../byacc-1.9/yacc
RANLIB=echo
ROOTDIR=..
#########################################################################


include Makefile.common
include Makefile.dependencies


#########################################################################
